// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "lyc,why"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/account/info": {
            "get": {
                "consumes": [
                    "application/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "获取账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "account_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2009:权限不足 2007:身份不存在 2008:身份验证失败 2010:账号不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.GetAccountByID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/account/infos/name": {
            "get": {
                "consumes": [
                    "application/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "通过昵称模糊查找账户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "Page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "PageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "account_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败 2010:账号不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.GetAccountsByName"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/account/infos/user": {
            "get": {
                "tags": [
                    "account"
                ],
                "summary": "创建账户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1003:系统错误 2008:身份验证失败 2010:账号不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.GetAccountsByUserID"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/account/update": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "更新账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "账号信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/application/accept": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "被申请者同意好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "需要同意的申请",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AcceptApplication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败 2010:账号不存在 3002:申请不存在 3004:重复操作申请",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/application/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "发起好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "发起好友申请",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateApplicationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2001:鉴权失败 5003:好友已经存在 5004:不能添加自己为好友",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "删除已经发送的好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除已经发起的申请",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeleteApplicationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2001:鉴权失败 ",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/application/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "账户查看和自身相关的好友申请(不论是申请者还是被申请者)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "Page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "PageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1003:系统错误 2007:身份不存在 2008:身份验证失败 2010:账号不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.ApplicationsList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/application/refuse": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "被申请者拒绝好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "需要拒绝的申请",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RefuseApplication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败 2010:账号不存在 3002:申请不存在 3004:重复操作申请",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/v1/account//infos/user": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "获取用户的所有账号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.TotalAccountsReply"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/account/deleteAccount/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "删除账户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "删除账号的ID",
                        "name": "accountID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 ",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/v1/account/getToken/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "获取账户令牌",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "删除账号的ID",
                        "name": "accountID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/common.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/email/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "判断邮箱是否被注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "email",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CheckEmailExist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 ",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/v1/email/send": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "发送邮件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "email",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 3001:邮箱已经注册 3002:邮件发送频繁，请稍后再试",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "用户登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 3001:邮箱已经注册 ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.LoginReply"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "用户注册信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 3001:邮箱已经注册 ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.State"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/reply.LoginReply"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Logout"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 3001:邮箱已经注册 ",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        },
        "/api/v1/user/modifyPassword": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModifyPassword"
                ],
                "summary": "用户更改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "x-token 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ReqModifyPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "1001:参数有误 1003:系统错误 3001:邮箱已经注册 ",
                        "schema": {
                            "$ref": "#/definitions/common.State"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.State": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "失败时返回空"
                },
                "status_code": {
                    "description": "状态码，0-成功，其他值-失败",
                    "type": "integer"
                },
                "status_msg": {
                    "description": "返回状态描述",
                    "type": "string"
                }
            }
        },
        "common.Token": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "reply.AccountInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "reply.AccountInfoReply": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "reply.ApplicationsList": {
            "type": "object",
            "properties": {
                "applicationList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reply.GetApplication"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "reply.EasyAccount": {
            "type": "object",
            "properties": {
                "accountID": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "reply.GetAccountByID": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "reply.GetAccountsByName": {
            "type": "object",
            "properties": {
                "accountInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reply.AccountInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "reply.GetAccountsByUserID": {
            "type": "object",
            "properties": {
                "accountInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reply.AccountInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "reply.GetApplication": {
            "type": "object",
            "properties": {
                "applicant": {
                    "$ref": "#/definitions/reply.EasyAccount"
                },
                "applyMsg": {
                    "type": "string"
                },
                "receiver": {
                    "$ref": "#/definitions/reply.EasyAccount"
                },
                "refuseMsg": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "reply.LoginReply": {
            "type": "object",
            "properties": {
                "AccessToken": {
                    "type": "string"
                },
                "Payload": {
                    "$ref": "#/definitions/token.Payload"
                },
                "RefreshToken": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "reply.TotalAccountsReply": {
            "type": "object",
            "properties": {
                "accountInfos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/reply.AccountInfoReply"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "request.AcceptApplication": {
            "type": "object",
            "required": [
                "applicant_id"
            ],
            "properties": {
                "applicant_id": {
                    "type": "integer"
                }
            }
        },
        "request.CheckEmailExist": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "检查是否存在的邮箱",
                    "type": "string"
                }
            }
        },
        "request.CreateApplicationReq": {
            "type": "object",
            "required": [
                "accountID",
                "applicationMsg"
            ],
            "properties": {
                "accountID": {
                    "type": "integer"
                },
                "applicationMsg": {
                    "type": "string"
                }
            }
        },
        "request.DeleteApplicationReq": {
            "type": "object",
            "required": [
                "accountID"
            ],
            "properties": {
                "accountID": {
                    "type": "integer"
                }
            }
        },
        "request.Login": {
            "type": "object",
            "required": [
                "email",
                "loginType"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "email_code": {
                    "description": "之间发送的邮箱验证码",
                    "type": "string"
                },
                "loginType": {
                    "description": "1表示使用邮箱登录, 2表示使用密码登录",
                    "type": "integer"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "request.RefuseApplication": {
            "type": "object",
            "required": [
                "applicant_id"
            ],
            "properties": {
                "applicant_id": {
                    "type": "integer"
                },
                "refuse_msg": {
                    "type": "string"
                }
            }
        },
        "request.Register": {
            "type": "object",
            "required": [
                "email",
                "email_code",
                "mobile",
                "rePassword"
            ],
            "properties": {
                "email": {
                    "description": "注册邮箱",
                    "type": "string"
                },
                "email_code": {
                    "description": "邮箱验证码",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "maxLength": 12,
                    "minLength": 3
                },
                "rePassword": {
                    "description": "第二次输出密码",
                    "type": "string"
                }
            }
        },
        "request.ReqModifyPassword": {
            "type": "object",
            "required": [
                "emailCode",
                "password"
            ],
            "properties": {
                "emailCode": {
                    "description": "身份认证的验证码",
                    "type": "string"
                },
                "password": {
                    "description": "修改成的密码",
                    "type": "string"
                }
            }
        },
        "request.SendEmail": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "发送邮箱的验证码",
                    "type": "string"
                }
            }
        },
        "request.UpdateAccount": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "token.Payload": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "可以是用户或者是账户",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "expired-at": {
                    "type": "string"
                },
                "id": {
                    "description": "用于管理每个JWT",
                    "type": "string"
                },
                "issued-at": {
                    "description": "创建时间用于检验",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8084",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "chat",
	Description:      "在线聊天系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
