basePath: /
definitions:
  common.State:
    properties:
      data:
        description: 失败时返回空
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  reply.Account:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      gender:
        type: integer
      id:
        type: integer
      name:
        type: string
      signature:
        type: string
      user_id:
        type: integer
    type: object
  reply.GetAccountByID:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      gender:
        type: integer
      id:
        type: integer
      name:
        type: string
      signature:
        type: string
      user_id:
        type: integer
    type: object
  reply.GetAccountsByName:
    properties:
      account:
        items:
          $ref: '#/definitions/reply.Account'
        type: array
      total:
        type: integer
    type: object
  reply.LoginReply:
    properties:
      AccessToken:
        type: string
      Payload:
        $ref: '#/definitions/token.Payload'
      RefreshToken:
        type: string
      UserID:
        type: integer
    type: object
  request.CheckEmailExist:
    properties:
      email:
        description: 检查是否存在的邮箱
        type: string
    required:
    - email
    type: object
  request.Login:
    properties:
      email:
        description: 邮箱
        type: string
      email_code:
        description: 之间发送的邮箱验证码
        type: string
      loginType:
        description: 1表示使用邮箱登录, 2表示使用密码登录
        type: integer
      password:
        description: 密码
        type: string
    required:
    - email
    - loginType
    type: object
  request.Register:
    properties:
      email:
        description: 注册邮箱
        type: string
      email_code:
        description: 邮箱验证码
        type: string
      mobile:
        description: 手机
        type: string
      password:
        description: 密码
        maxLength: 12
        minLength: 3
        type: string
      rePassword:
        description: 第二次输出密码
        type: string
    required:
    - email
    - email_code
    - mobile
    - rePassword
    type: object
  request.ReqModifyPassword:
    properties:
      emailCode:
        description: 身份认证的验证码
        type: string
      password:
        description: 修改成的密码
        type: string
    required:
    - emailCode
    - password
    type: object
  request.SendEmail:
    properties:
      email:
        description: 发送邮箱的验证码
        type: string
    required:
    - email
    type: object
  token.Payload:
    properties:
      content:
        description: 可以是用户或者是账户
        items:
          type: integer
        type: array
      expired-at:
        type: string
      id:
        description: 用于管理每个JWT
        type: string
      issued-at:
        description: 创建时间用于检验
        type: string
    type: object
host: 127.0.0.1:8084
info:
  contact: {}
  description: 在线聊天系统
  license:
    name: lyc,why
  title: chat
  version: "1.0"
paths:
  /api/account/info:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - in: query
        minimum: 1
        name: account_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2009:权限不足 2007:身份不存在 2008:身份验证失败 2010:账号不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountByID'
              type: object
      summary: 获取账户信息
      tags:
      - account
  /api/account/infos/name:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - in: query
        name: Page
        type: integer
      - in: query
        name: PageSize
        type: integer
      - in: query
        name: account_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 2007:身份不存在 2008:身份验证失败 2010:账号不存在
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.GetAccountsByName'
              type: object
      summary: 通过昵称模糊查找账户
      tags:
      - account
  /api/v1/email/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - description: email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CheckEmailExist'
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 '
          schema:
            $ref: '#/definitions/common.State'
      summary: 判断邮箱是否被注册
      tags:
      - email
  /api/v1/email/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - description: email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SendEmail'
      produces:
      - application/json
      responses:
        "200":
          description: 1001:参数有误 1003:系统错误 3001:邮箱已经注册 3002:邮件发送频繁，请稍后再试
          schema:
            $ref: '#/definitions/common.State'
      summary: 发送邮件
      tags:
      - email
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 3001:邮箱已经注册 '
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.LoginReply'
              type: object
      summary: 用户登录
      tags:
      - login
  /api/v1/user/logout:
    get:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 3001:邮箱已经注册 '
          schema:
            $ref: '#/definitions/common.State'
      summary: 用户登出
      tags:
      - Logout
  /api/v1/user/modifyPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ReqModifyPassword'
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 3001:邮箱已经注册 '
          schema:
            $ref: '#/definitions/common.State'
      summary: 用户更改密码
      tags:
      - ModifyPassword
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: x-token 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: '1001:参数有误 1003:系统错误 3001:邮箱已经注册 '
          schema:
            allOf:
            - $ref: '#/definitions/common.State'
            - properties:
                data:
                  $ref: '#/definitions/reply.LoginReply'
              type: object
      summary: 用户注册
      tags:
      - register
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
